### ISSUE TITLE
Melhorias

### ISSUE THREAD

**Issue by kyriosdata** [antoni-s/i-2018#5]
- Atividadas 8, 7, 6 não implementadas conforme a especificação. 
- Acrescente nota de copyright no início de cada arquivo fonte. 
- Testes estão restritos a questões "sintáticas" do código. 
- Baixa coesão de alguns métodos, por exemplo, persistir em Serializacao, não apenas "persiste", como o nome sugere, mas cria o objeto a ser persistido, verifica a integridade do nome do arquivo no qual será persistido e, de fato, persiste, seguido de um sempre "true". O true não faz muito sentido, pois deveria representar o caso de sucesso e, em tempo, há muitos cenários para falhas (exceções), que deveriam retornar false por uma questão de consistência. 
- Em GitApi:
  - Gson oferece o método fromJson(InputStream, Class) de forma que as linhas 34-43 podem ser substituídas por versão bem mais simples. Isso incluiria as linhas 45 e 46. 
  - Método buscaArmazenaAvatar, até no nome demonstra a fraca coesão. E observe que o nome não diz tudo que ele faz. Precisamos melhorar o design.

**Comment by aassilva** [comment]
Nos tópico 1 e 2 já fechados foram feito algumas melhorias nos testes e no código fonte.
O tópico 3 está em construção.
Todas as alterações estão sendo feitas na branch "topico3" conforme recomendação.
